spring:
  application:
    name: "playground"
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:./test
    username: sa
    password: password
    driver-class-name: org.h2.Driver

server:
  port: 8999